/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ChartType, DataModel, Param } from "@senx/discovery-widgets";
export namespace Components {
    interface DiscoveryPluginCsvExport {
        "options": Param | string;
        /**
          * Tile attributes
         */
        "result": DataModel | string;
        "type": ChartType;
    }
}
declare global {
    interface HTMLDiscoveryPluginCsvExportElement extends Components.DiscoveryPluginCsvExport, HTMLStencilElement {
    }
    var HTMLDiscoveryPluginCsvExportElement: {
        prototype: HTMLDiscoveryPluginCsvExportElement;
        new (): HTMLDiscoveryPluginCsvExportElement;
    };
    interface HTMLElementTagNameMap {
        "discovery-plugin-csv-export": HTMLDiscoveryPluginCsvExportElement;
    }
}
declare namespace LocalJSX {
    interface DiscoveryPluginCsvExport {
        "options"?: Param | string;
        /**
          * Tile attributes
         */
        "result"?: DataModel | string;
        "type"?: ChartType;
    }
    interface IntrinsicElements {
        "discovery-plugin-csv-export": DiscoveryPluginCsvExport;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "discovery-plugin-csv-export": LocalJSX.DiscoveryPluginCsvExport & JSXBase.HTMLAttributes<HTMLDiscoveryPluginCsvExportElement>;
        }
    }
}
